### ISSUE TITLE
Can't load model?

### ISSUE THREAD

**Issue by flitert** [kitsunde/CIUnit#24]
[CIUnit] PHP Error: Notice - Undefined property: Login::$comm_model File Path: c
ontrollers/Login.php (line: 291)

Code:
```php
class Login extends CI_Controller {
  public function __construct(){
    parent::__construct();
    $this->load->model('comm_model');
    $this->load->library('form_validation');
  }
public function valadate_selfuser(){
$count = $this->is_available($check_arr,'custom');
}
public function is_available($arr,$table){
    $count = $this->comm_model->count_by_where($arr,$table);
    return $count;
  }
}
```

Test Code:

```php
public function test_valadate_selfuser_1()
    {
    	$_POST['username'] = 'test@gmail.com';
    	$_POST['usertype'] = 0;
        $result = $this->CI->valadate_selfuser(1);
        $expected_result = array('status'=>'0','text'=>'');
    	$this->expectOutputString(json_encode($expected_result));
    }
```

**Comment by Celc** [comment]
* What version of CI are you using?
* Does the Login view work normally?
* Has the constructor actually fired?
* What does the rest of your test class look like?

**Comment by flitert** [comment]
- I'm using CI3

- Login view work well when I visit this controller by url.
 
- i'm not sure if the constructor was fired.  

		D:\htdocs\myproject\front_tests>phpunit
		[CIUnit] PHP Error: Notice - Only variable references should be returned by refe
		rence File Path: core/Common.php (line: 294)
		PHPUnit 4.5.1 by Sebastian Bergmann and contributors.
		
		Configuration read from D:\htdocs\myproject\front_tests\phpunit.xml
		
		[CIUnit] PHP Error: Notice - Undefined property: Login::$comm_model File Path: c
		ontrollers/Login.php (line: 293)
		
		Fatal error: Call to a member function count_by_where() on null in D:\htdocs\myproject
		\front\controllers\Login.php on line 293

**Comment by flitert** [comment]
Login_test controller 

class Login_Test extends CIUnit_TestCase
{
    public function setUp()
    {
        $this->CI = set_controller('Login');
    }

    public function test_validate_user_1()
    {
    	$_POST['username'] = 'test@gmail.com';
    	$_POST['usertype'] = 0;
        $result = $this->CI->valadate_selfuser(1);
        $expected_result = array('status'=>'0','text'=>'');
    	$this->expectOutputString(json_encode($expected_result));
    }
}

**Comment by Celc** [comment]
Ah, CIUnit hasn't been updated for CI3. I don't expect it to work.

**Comment by flitert** [comment]
ur , thanks for your helping

**Comment by flitert** [comment]
Thanks a lot.But I has got another problem when I change my project to CI2.2(pure CI framework) from CI3.

error code:
D:\xampp\htdocs\tests>phpunit

Fatal error: Class 'Spyc' not found in D:\xampp\htdocs\src\bootstrap_phpunit.php
 on line 243


so,I delete this line then CIUnit runs well.
I only find 'public static $spyc;' in CIUnit.php at line 43.

 Is there a tutorial for CIUnit? Thanks you for help.  :+1: >

**Comment by Celc** [comment]
@flitert Only what's in the readme file. spyc should be installed when you use comoser: https://github.com/Celc/CIUnit/blob/master/composer.json

**Comment by kitsunde** [comment]
Closing this this because of inactivity
