### ISSUE TITLE
Composer install failing

### ISSUE THREAD

**Issue by vikingjs** [kitsunde/CIUnit#29]
I'm getting the following error message when I run my install: 

```
Failed to download celc/ciunit from source: Failed to execute git clone --no-checkout 'git@github.com:Celc/CIUnit.git' '/Users/Shared/Jenkins/Home/jobs/Dispatch/workspace/vendor/celc/ciunit' && cd '/Users/Shared/Jenkins/Home/jobs/Dispatch/workspace/vendor/celc/ciunit' && git remote add composer 'git@github.com:Celc/CIUnit.git' && git fetch composer
```

This started happening after I ran `composer update` on my local machine then saved the composer.lock file to our scm. The Jenkins build robot doesn't seem to be able to clone the latest release. It was able to clone the previous one without problems.

**Comment by kitsunde** [comment]
I've updated the repo on packagist and this works for me:

    composer require Celc/CIUnit
    composer update

Are you still having the same problem? This is what my `composer.json` looks like:

```json
{
    "name": "kitsunde/development",
    "authors": [
        {
            "name": "Kit Sunde",
            "email": "kitsunde@gmail.com"
        }
    ],
    "require": {
        "Celc/CIUnit": "~1.0"
    }
}
```

I'd could update the package name to `kitsunde/CIUnit` in `composer.json` but I'm worried it'll break the package for everyone.

**Comment by kitsunde** [comment]
Actually looking at your failing command:

```bash
git clone --no-checkout 'git@github.com:Celc/CIUnit.git' '/Users/Shared/Jenkins/Home/jobs/Dispatch/workspace/vendor/celc/ciunit' && 
cd '/Users/Shared/Jenkins/Home/jobs/Dispatch/workspace/vendor/celc/ciunit' && 
git remote add composer 'git@github.com:Celc/CIUnit.git' && 
git fetch composer
```

There's no reason why that command should fail, this works locally on my computer:

```bash
git clone --no-checkout 'git@github.com:Celc/CIUnit.git' '~/foo/bar' && 
cd '~/foo/bar' && 
git remote add composer 'git@github.com:Celc/CIUnit.git' && 
git fetch composer
```

You might want to run the command logged in as whatever user is running that and check if you have git or write access to that folder.

**Comment by vikingjs** [comment]
It works now; I ran `composer update` on my local machine, and the changes to the composer.lock file since yesterday then properly allowed `composer install` to work on the build machine. So updating the repo seems to have fixed it. Thanks for your swift attention!

Only marginally related - I'm using "dev-master" rather than "~1.0" - should I change it?

**Comment by kitsunde** [comment]
@vikingjs Cool, cool. Nah, just stick to dev-master no special effort went into that version number except that composer complained about lacking stable just now so I tagged a release.
